server:
    port: 7102
Spring:
    application:
        name: spring-cloud-eureka-client
eureka:
    client:
        serviceUrl:
            defaultZone: http://pustian.eureka.server0:8102/eureka/,http://pustian.eureka.server1:8202/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
        appname: spring-cloud-eureka-client-0
        preferIpAddress: true
