server:
    port: 8001
spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/pustian/spring-cloud.git
                    searchPaths: ./spring-cloud-config/spring-cloud-config-repo
