server:
    port: 8001
spring:
    application:
        name: misc-config
    # EnvironmentRepositoryConfiguration.java 支持默认Git加载， 本地开发环境， svn环境
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    # file:E:\\Java\\Workspaces\\sts\\doc\\file\\config 或是 classpath:/config
                    searchLocations: file:C:\\workspace\\idea\\Exce-Learn\\spring-cloud\\misc-config-repo
#默认git支持
#spring:
#    cloud:
#        config:
#            server:
#                git:
#                    uri: https://github.com/pustian/spring-cloud.git
#                    searchPaths: ./spring-cloud-config/spring-cloud-config-repo