server:
    port: 8102
spring:
    application:
        name: spring-cloud-eureka-server
eureka:
    instance:
        hostname: pustian.eureka.server0
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        serviceUrl:
            defaultZone: http://pustian.eureka.server1:8202/eureka/
