server:
    port: 1111
eureka:
    client:
        healthcheck:
            enabled: true
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://pusen:tian@localhost:8001/eureka/ # username:passwd@localhost:8002/eureka/
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        # hostname:
        healthcheck:
          enabled: true

